version: 2.1

resources:
  defaults: &defaults
    docker:
      - image: cimg/node:14.19.2
      - image: cimg/postgres:13.6

    working_directory: ~/slack-app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn 
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build react app
          command: yarn build
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test-with-reporter
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/results.xml"
      - store_artifacts:
          path: test-results/jest/results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results
