version: 2
jobs:
  build:
    working_directory: ~/slack-app
    docker:
      - image: circleci/node:8.9.4
      - image: postgres:10.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn 
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build react app
          command: yarn build
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test-with-reporter
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml