version: 2
jobs:
  build:
    working_directory: ~/slack-app
    docker:
      - image: circleci/node:4.8.2
      - image: postgres:10.4
    steps:
      - checkout
      - run:
          name: Build and run client
          command: npm install && npm run build 
      - run:
          name: Build and run server
          working_directory: ~/slack-app/server
          command: npm install && node ./bin/www